---
ansiple_python_interpreter: /usr/bin/python3
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/NectarGroupKey
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

remote_working_directory: /home/ubuntu/COMP90024
remote_working_directory_big_data: /home/ubuntu/COMP90024/COMP90024

repository_name: ccc_assign2_group

git_repo: /home/ubuntu/COMP90024/ccc_assign2_group

couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: '3.0.0'
cluster_name: '_cluster_setup'
couchdb_container_name: 'couchdb_'
couchdb_port: 5984
couchdb_db_name: "live-tweets"
couchdb_config_path: /home/ubuntu/couchdb/etc
couchdb_share: 4
couchdb_replica: 3
cluster_communication_port_min: 9100
cluster_communication_port_max: 9102